import "./globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Sans_Condensed } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/components/providers/AuthProvider";
import { ModalProvider } from "@/components/providers/ModalProvider";
import SellerProvider from "@/components/providers/SellerProvider";
import HubProvider from "@/components/providers/HubProvider";
import { LoadingProvider } from "@/components/providers/LoadingProvider";

const inter = IBM_Plex_Sans_Condensed({
  subsets: ["cyrillic-ext"],
  weight: "500"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoadingProvider>
          <AuthProvider>
            <SellerProvider>
              <HubProvider>
                <Toaster />
                <ModalProvider />
                  {children}
              </HubProvider>
            </SellerProvider>
          </AuthProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
